[package]
name = "mgt"
description = "Git tools that enable easy bidirectional sync between multiple repositories"
# please make sure version is always on line 5, otherwise CI will break ¯\_(ツ)_/¯
version = "2.6.0"
authors = ["Nikita Skobov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
clap = "2.33"
git-url-parse = "0.3.0"
die = { path="die" }

[features]
gittests = []
